export const OWNER = 'Dmitry'
export const TITLE = `IMDB + ${OWNER}'s Top 8 Movies`
export const GITHUB = 'https://github.com/dmitrygalperin/project3'
export const MOVIES = [
    {
      title:	'The Shawshank Redemption',
      iscore:	9.3,
      rating:	'R',
      runtime:	142,
      released:	new Date('1994', '10', '14'),
      country:	'USA',
      posters:	['img/shawshank.jpg','img/shawshank2.jpg','img/shawshank3.jpg'],
      imdb:		'http://www.imdb.com/title/tt0111161',
      website:	'https://www.facebook.com/ShawshankRedemptionFilm',
      likes:	1021,
      dislikes:	122,
      posterindex: 0
	},
    {
      title:	'The Godfather',
      iscore:	9.2,
      rating:	'R',
      runtime:	175,
      released:	new Date('1972', '03', '24'),
      country:	'USA',
      posters:	['img/godfather.jpg','img/godfather_2.jpg','img/godfather_3.jpg'],
      imdb:		'[http://www.imdb.com/title/tt0068646',
      website:	'https://www.facebook.com/thegodfather',
      likes:	928,
      dislikes:	109,
      posterindex: 0
	},
    {
      title:	'The Godfather: Part II',
      iscore:	9.0,
      rating:	'R',
      runtime:	202,
      released:	new Date('1974', '12', '20'),
      country:	'USA',
      posters:	['img/godfather2.jpg','img/godfather2_2.jpg'],
      imdb:		'http://www.imdb.com/title/tt0071562',
      website:	'https://www.facebook.com/thegodfather',
      likes:	855,
      dislikes:	99,
      posterindex: 0
	},
    {
      title:	'The Dark Knight',
      iscore:	8.9,
      rating:	'PG-13',
      runtime:	152,
      released:	new Date('2008', '07', '18'),
      country:	'USA',
      posters:	['img/darkknight.jpg','img/darkknight2.jpg'],
      imdb:		'http://www.imdb.com/title/tt0468569',
      website:	'http://www.42entertainment.com/work/whysoserious',
      likes:	828,
      dislikes:	127,
      posterindex: 0
	},
    {
      title:	'Schindler\'s List',
      iscore:	8.9,
      rating:	'R',
      runtime:	195,
      released:	new Date('1993', '11', '30'),
      country:	'USA',
      posters:	['img/schindlerslist.jpg'],
      imdb:		'http://www.imdb.com/title/tt0108052',
      website:	'https://www.uphe.com/schindlers-list',
      likes:	812,
      dislikes:	101,
      posterindex: 0
  },
    {
      title:	'Office Space',
      iscore:	7.8,
      rating:	'R',
      runtime:	89,
      released:	new Date('1999', '02', '19'),
      country:	'USA',
      posters:	['img/officespace1.jpg'],
      imdb:		'http://www.imdb.com/title/tt0151804/',
      website:	'https://en.wikipedia.org/wiki/Office_Space',
      likes:	950,
      dislikes:	80,
      posterindex: 0
	},
  {
    title:	'A Clockwork Orange',
    iscore:	8.3,
    rating:	'R',
    runtime:	136,
    released:	new Date('1972', '02', '02'),
    country:	'USA',
    posters:	['img/clockworkorange.jpg', 'img/clockworkorange2.jpg'],
    imdb:		'http://www.imdb.com/title/tt0066921/',
    website:	'https://en.wikipedia.org/wiki/A_Clockwork_Orange_(film)',
    likes:	1050,
    dislikes:	70,
    posterindex: 0
  },
  {
    title:	'Cell 211',
    iscore:	7.7,
    rating:	'N/A',
    runtime:	113,
    released:	new Date('2009', '11', '06'),
    country:	'Spain',
    posters:	['img/cell211.jpg', 'img/cell2112.jpg'],
    imdb:		'http://www.imdb.com/title/tt1242422/',
    website:	'https://en.wikipedia.org/wiki/Cell_211',
    likes:	999,
    dislikes:	71,
    posterindex: 0
  }
]
